name = "sophisticated_cyan_shrew-e647"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "sophisticated_cyan_shrew-e647_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "sophisticated_cyan_shrew-e647.wasm"
command = "npm run build:release"
